### ISSUE TITLE
Receive an error.

### ISSUE THREAD

**Issue by 0zul** [SCP-George/Ditto#1]
```shell
(node:32386) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'trim' of undefined
[0]     at /app/server.js:14:37
[0]     at Layer.handle [as handle_request] (/rbd/pnpm-volume/c75583e6-4c0b-43f1-b5cf-9673577e91fc/node_modules/.registry.npmjs.org/express/4.17.1/node_modules/express/lib/router/layer.js:95:5)
[0]     at next (/rbd/pnpm-volume/c75583e6-4c0b-43f1-b5cf-9673577e91fc/node_modules/.registry.npmjs.org/express/4.17.1/node_modules/express/lib/router/route.js:137:13)
[0]     at Route.dispatch (/rbd/pnpm-volume/c75583e6-4c0b-43f1-b5cf-9673577e91fc/node_modules/.registry.npmjs.org/express/4.17.1/node_modules/express/lib/router/route.js:112:3)
[0]     at Layer.handle [as handle_request] (/rbd/pnpm-volume/c75583e6-4c0b-43f1-b5cf-9673577e91fc/node_modules/.registry.npmjs.org/express/4.17.1/node_modules/express/lib/router/layer.js:95:5)
[0]     at /rbd/pnpm-volume/c75583e6-4c0b-43f1-b5cf-9673577e91fc/node_modules/.registry.npmjs.org/express/4.17.1/node_modules/express/lib/router/index.js:281:22
[0]     at Function.process_params (/rbd/pnpm-volume/c75583e6-4c0b-43f1-b5cf-9673577e91fc/node_modules/.registry.npmjs.org/express/4.17.1/node_modules/express/lib/router/index.js:335:12)
[0]     at next (/rbd/pnpm-volume/c75583e6-4c0b-43f1-b5cf-9673577e91fc/node_modules/.registry.npmjs.org/express/4.17.1/node_modules/express/lib/router/index.js:275:10)
[0]     at expressInit (/rbd/pnpm-volume/c75583e6-4c0b-43f1-b5cf-9673577e91fc/node_modules/.registry.npmjs.org/express/4.17.1/node_modules/express/lib/middleware/init.js:40:5)
[0]     at Layer.handle [as handle_request] (/rbd/pnpm-volume/c75583e6-4c0b-43f1-b5cf-9673577e91fc/node_modules/.registry.npmjs.org/express/4.17.1/node_modules/express/lib/router/layer.js:95:5)
[0]     at trim_prefix (/rbd/pnpm-volume/c75583e6-4c0b-43f1-b5cf-9673577e91fc/node_modules/.registry.npmjs.org/express/4.17.1/node_modules/express/lib/router/index.js:317:13)
[0]     at /rbd/pnpm-volume/c75583e6-4c0b-43f1-b5cf-9673577e91fc/node_modules/.registry.npmjs.org/express/4.17.1/node_modules/express/lib/router/index.js:284:7
[0]     at Function.process_params (/rbd/pnpm-volume/c75583e6-4c0b-43f1-b5cf-9673577e91fc/node_modules/.registry.npmjs.org/express/4.17.1/node_modules/express/lib/router/index.js:335:12)
[0]     at next (/rbd/pnpm-volume/c75583e6-4c0b-43f1-b5cf-9673577e91fc/node_modules/.registry.npmjs.org/express/4.17.1/node_modules/express/lib/router/index.js:275:10)
[0]     at query (/rbd/pnpm-volume/c75583e6-4c0b-43f1-b5cf-9673577e91fc/node_modules/.registry.npmjs.org/express/4.17.1/node_modules/express/lib/middleware/query.js:45:5)
[0]     at Layer.handle [as handle_request] (/rbd/pnpm-volume/c75583e6-4c0b-43f1-b5cf-9673577e91fc/node_modules/.registry.npmjs.org/express/4.17.1/node_modules/express/lib/router/layer.js:95:5)
[0]     at trim_prefix (/rbd/pnpm-volume/c75583e6-4c0b-43f1-b5cf-9673577e91fc/node_modules/.registry.npmjs.org/express/4.17.1/node_modules/express/lib/router/index.js:317:13)
[0]     at /rbd/pnpm-volume/c75583e6-4c0b-43f1-b5cf-9673577e91fc/node_modules/.registry.npmjs.org/express/4.17.1/node_modules/express/lib/router/index.js:284:7
[0]     at Function.process_params (/rbd/pnpm-volume/c75583e6-4c0b-43f1-b5cf-9673577e91fc/node_modules/.registry.npmjs.org/express/4.17.1/node_modules/express/lib/router/index.js:335:12)
[0]     at next (/rbd/pnpm-volume/c75583e6-4c0b-43f1-b5cf-9673577e91fc/node_modules/.registry.npmjs.org/express/4.17.1/node_modules/express/lib/router/index.js:275:10)
[0]     at Function.handle (/rbd/pnpm-volume/c75583e6-4c0b-43f1-b5cf-9673577e91fc/node_modules/.registry.npmjs.org/express/4.17.1/node_modules/express/lib/router/index.js:174:3)
[0]     at Function.handle (/rbd/pnpm-volume/c75583e6-4c0b-43f1-b5cf-9673577e91fc/node_modules/.registry.npmjs.org/express/4.17.1/node_modules/express/lib/application.js:174:10)
[0] (node:32386) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
```
This is the error I get from serverfile.js

**Comment by ghost** [comment]
You did not receive a tokens property in the request
